apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: restaurantapp
  labels:
    app: restaurantapp
spec:
  replicas: 2 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: restaurantapp
  template:
    metadata:
      labels:
        app: restaurantapp
    spec:
      containers:
        - name: restaurantapp
          image: codedecode25/restaurant:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 9091 #

          env: # Environment variables supplied to the Pod
            - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
              valueFrom: # Get the value of environment variable from kubernetes secrets
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: restaurantdb_url
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: restaurantdb
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-user-username

---

apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: restaurantapp
  type: NodePort